Fixing reassignment error for tutorial2
250417
When applied "data = spod.get_data(data)", it returns the following error:
    TypeError: invalid indexer array, does not have integer dtype: array(None, dtype=object)
    Why? reassignment occurs for data, and the type of data is changed to object.
Fixed: data = spod.get_data(data.values)

Cannot cd to correct dir (py version only)
    No like ipynb, py might be performed outside the tutorial2 directory.
Fixed: detect and cd to the correct directory before running.